const CLOUD_DEFAULT_ROOT_FOLDER_NAME = 'CLOUD_DEFAULT_ROOT_FOLDER_NAME';
const CLOUD_FILE_NAME_CONFIG      = 'CLOUD_FILE_NAME_CONFIG';
const CLOUD_FILE_NAME_CLASS_STORE = 'CLOUD_FILE_NAME_CLASS_STORE';

module.exports = {
	CLOUD_FILE_NAME_CONFIG,
	CLOUD_FILE_NAME_CLASS_STORE,
	CLOUD_DEFAULT_ROOT_FOLDER_NAME
};
