
const BG_COLOR_BLUE = '#3f51b5';
const BG_COLOR_WARNING = '#ffeb3b';
const BG_COLOR_SUCCESS = '#2196f3';
const BG_COLOR_ERROR   = '#f50057';
const BG_COLOR_DEFAULT = '#e0e0e0';
const COLOR_WHITE      = '#fff';
const COLOR_BLACK      = '#000';

export {
	COLOR_BLACK,
	COLOR_WHITE,
	BG_COLOR_ERROR,
	BG_COLOR_WARNING,
	BG_COLOR_SUCCESS,
	BG_COLOR_DEFAULT,
	BG_COLOR_BLUE
};

