const PREFIX_UPDATE_LOCATION = 'UPDATE_LOCATION';
const PREFIX_MENU  = 'MENU';
const PREFIX_ALERT = 'ALERT';
const PREFIX_CONNECTION = 'CONNECTIONS';
const PREFIX_SEND_FORM = 'UPLOAD_FORM';
const PREFIX_DIALOG_ADD_TO_JSON = 'DIALOG_ADD_TO_JSON';
// TODO: Back
const PREFIX_EVENT_ROOM = 'SOCKET_EVENTS';

module.exports = {
	PREFIX_DIALOG_ADD_TO_JSON,
	PREFIX_EVENT_ROOM,
	PREFIX_CONNECTION,
	PREFIX_SEND_FORM,
	PREFIX_MENU,
	PREFIX_ALERT,
	PREFIX_UPDATE_LOCATION
};
