const PREFIX_UPDATE_LOCATION = 'UPDATE_LOCATION';
const PREFIX_MENU  = 'MENU';
const PREFIX_AUTH  = 'AUTH';
const PREFIX_ALERT = 'ALERT';
const PREFIX_CONNECTION = 'CONNECTIONS';
const PREFIX_CONNECTION_ADD = 'CONNECTION_ADD';
const PREFIX_SEND_FORM = 'SEND_FORM';
const PREFIX_EVENT_ROOM = 'SOCKET_EVENTS';

module.exports = {
	PREFIX_EVENT_ROOM,
	PREFIX_CONNECTION_ADD,
	PREFIX_CONNECTION,
	PREFIX_SEND_FORM,
	PREFIX_MENU,
	PREFIX_AUTH,
	PREFIX_ALERT,
	PREFIX_UPDATE_LOCATION
};
