const PREFIX_UPDATE_LOCATION = 'UPDATE_LOCATION';
const PREFIX_MENU  = 'MENU';
const PREFIX_ALERT = 'ALERT';
const PREFIX_CONNECTION = 'CONNECTIONS';
const PREFIX_SEND_FORM = 'UPLOAD_FORM';
const PREFIX_DIALOG_ADD_TO_JSON = 'DIALOG_ADD_TO_JSON';
const PREFIX_DIALOG_ADD_CLASS_DEPENDENCY = 'DIALOG_ADD_CLASS_DEPENDENCY';
const PREFIX_STEPS = 'STEPS';
const PREFIX_STEP_SETTINGS = 'STEP_SETTINGS';
const PREFIX_STEP_RESULT = 'STEP_RESULT_LIST';
const PREFIX_STEP_REPORT = 'STEP_REPORT';

module.exports = {
	PREFIX_DIALOG_ADD_CLASS_DEPENDENCY,
	PREFIX_STEP_REPORT,
	PREFIX_STEP_RESULT,
	PREFIX_STEP_SETTINGS,
	PREFIX_STEPS,
	PREFIX_DIALOG_ADD_TO_JSON,
	PREFIX_CONNECTION,
	PREFIX_SEND_FORM,
	PREFIX_MENU,
	PREFIX_ALERT,
	PREFIX_UPDATE_LOCATION
};
